### ISSUE TITLE
error on admin pages

### ISSUE THREAD

**Issue by mcgoooo** [spree-contrib/spree_paypal_express#38]
Hi there,

i seem to be having a problem with the spree paypal express plugin.

the version of spree i'm using is 0.70.1, and the spree paypal express is spree_paypal_express (1.0.1 bea1aa4)

when i go to a payment page, e.g.
*/admin/orders/R186775626/payments

it error's out with

ActionView::Template::Error (undefined method `params' for #YAML::Object:0x1376e9d70):
    13:       <td><%= link_to payment_method_name(payment), admin_order_payment_path(@order, payment) %></td>
    14:       <td><%= t(payment.state, :scope => :payment_states, :default => payment.state.capitalize) %></td>
    15:       <td>
    16:         <% payment.actions.each do |action| %>
    17:           <%= button_to t(action), fire_admin_order_payment_path(@order, payment, :e => action), :method => :put %>
    18:         <% end %>
    19:       </td>

any help sorting this would be awesome

**Comment by steveroot** [comment]
I think 1.0 versions won't work with 0.70 because of the name space changing.  There's a commit on Jan 3rd that says:

```
Correct Versionfile 
…
 master contains namespacing changes that don't work with 0.70.x. Need to 'revert' to October 8 for this to work
```

So perhaps in your Gemfile:

gem 'spree_paypal_express',
  :git => 'git@github.com:spree/spree_paypal_express.git,
  :ref => 'bea1aa48e0089083546bec4b19565a40e9a50a20'

and then run:
bundle update spree_paypal_express   to just update that gem, or bundle update to refresh everything

**Comment by LBRapid** [comment]
@mcgoooo Did specifying the right ref in your Gemfile resolve the issue for you?

**Comment by mcgoooo** [comment]
i just checked it and that is the commit id i'm using, sorry for the
confusion. unfortunately this does not solve it, sorry for the late
response.

On Sun, Feb 19, 2012 at 3:55 PM, Steve Root <
reply@reply.github.com
